export const ADD_TODO = 'ADD_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const START_DO_TODO = 'START_DO_TODO'
export const STOP_DO_TODO = 'STOP_DO_TODO'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SORT_TODOS = 'SORT_TODOS'